### PR TITLE
Adds support for importing wallets using private keys

### PR DESCRIPTION
**Pull request by noahlitvin**
Thanks for building this! I was looking to set up e2e tests locally that would interact with a node provisioned by hardhat, but realized I'd need to pass in a private key, rather than a mnemonic phrase, to connect a wallet. This PR adds support for this. The browser automation looks like [this](https://www.loom.com/share/fead844cb0a548bab94dbb11b30d204e).

If you're interested in merging, happy to make further updates. Let me know.

### CODE REVIEW

**Comment by drptbl** [comment]
@noahlitvin Thanks for good words, awesome work! I will take a look over weekend.

**Comment by drptbl** [comment]
@noahlitvin sorry for keeping you waiting! should be finished by tomorrow.

**Review by drptbl — APPROVED** [review]
LGTM after refactor, thanks for great work!

**Comment by drptbl** [comment]
@noahlitvin released as `@synthetixio/synpress@0.9.25-beta.10`

will be promoted as production release (`0.9.26`) later this week, cheers!

**Comment by noahlitvin** [comment]
Amazing, thanks!

**Pull request merged**
