### PR TITLE
Allow to select all accounts when accepting dApp connection

### PR DESCRIPTION
**Pull request by shawnwang0715**
Seems that nobody has created a PR for this, so I try to contribute this...

Usage: `cy.acceptMetamaskAccess(true);`

### CODE REVIEW

**Comment by kabaneridev** [comment]
hi @shawnwang0715, can you add 1 fix in this PR for 2 updated selectors?

code
pages/metamask/notification-page.js
```
const confirmSignatureRequestButton = `${notificationPage} .request-signature__footer__sign-button`;
const rejectSignatureRequestButton = `${notificationPage} .request-signature__footer__cancel-button`;
```
should be changed to
```
const confirmSignatureRequestButton = `${notificationPage} .signature-request-footer :last-child`;
const rejectSignatureRequestButton = `${notificationPage} .signature-request-footer :first-child`;
```

because without that method `confirmMetamaskSignatureRequest()` fails.

**Comment by shawnwang0715** [comment]
@kabaneridev I added the code you suggested. But did my PR break the confirmMetamaskSignatureRequest() feature? Why?

**Comment by maxhoheiser** [comment]
Hi, I am also depending on this feature, since I want to test my dapp with both a admin account (account 2) and a regular user (account 3), but I can only connect to one of both, and if switching to the other, it is not connected to the dapp.
Any workaround for that issue?

Cheers Max

**Comment by maxhoheiser** [comment]
> hi @shawnwang0715, can you add 1 fix in this PR for 2 updated selectors?
> 
> code pages/metamask/notification-page.js
> 
> ```
> const confirmSignatureRequestButton = `${notificationPage} .request-signature__footer__sign-button`;
> const rejectSignatureRequestButton = `${notificationPage} .request-signature__footer__cancel-button`;
> ```
> 
> should be changed to
> 
> ```
> const confirmSignatureRequestButton = `${notificationPage} .signature-request-footer :last-child`;
> const rejectSignatureRequestButton = `${notificationPage} .signature-request-footer :first-child`;
> ```
> 
> because without that method `confirmMetamaskSignatureRequest()` fails.

actually, with the changes it fails for me, but with the original version:
```
const confirmSignatureRequestButton = `${notificationPage} .request-signature__footer__sign-button`;
const rejectSignatureRequestButton = `${notificationPage} .request-signature__footer__cancel-button`;
```
it works

**Comment by drptbl** [comment]
Hey @shawnwang0715, thank you very much for contribution. Sorry for late response, I have been affected by situation on Ukraine, so I couldn't work past 2 weeks.

Cheers,
Jakub.

**Comment by drptbl** [comment]
It has been released as `@synthetixio/synpress@1.1.2-beta.3`.

**Comment by shawnwang0715** [comment]
@drptbl thank you so much. I hope you are all safe over there!

**Pull request merged**
