### PR TITLE
Upgrade Cypress to v10 and puppeteer to v15

### PR DESCRIPTION
**Pull request by maximgeerinck**
# Description

- Upgrade Cypress to v10
- Upgrade puppeteer to v15
- Make tests work standalone

### CODE REVIEW

**Comment by rohaanmalik** [comment]
upgrade cypress to >10.2.x version so that Mac M1 users could use this package

**Review by GustavoRSSilva — APPROVED** [review]

**Comment by ezpuzz** [comment]
I'm getting a strange error:

```
Could not find a Cypress configuration file.

We looked but did not find a synpress.json file in this folder: /home/emory/app/tests/synpress
```

The file is there and synpress 1.2.0 works fine.

**Review by ezpuzz — APPROVED** [review]

**Comment by Afitzy98** [comment]
It would be great to get this merged, facing a lot of issues recently which I think are stemming from this.

**Comment by hardingjam** [comment]
I'm working from this commit currently, would be great if it can be merged so I can keep up-to-date with npm versions.

**Comment by maximgeerinck** [comment]
I need a maintainer to approve

**Comment by svitekpavel** [comment]
@maximgeerinck I'm getting the following problem when I checked out this commit:

```
Could not find a Cypress configuration file.

We looked but did not find a tsconfig.json file in this folder: <project-path>/tests/e2e
```

Have you seen this problem?

**Comment by maximgeerinck** [comment]
> @maximgeerinck I'm getting the following problem when I checked out this commit:
> 
> ```
> Could not find a Cypress configuration file.
> 
> We looked but did not find a tsconfig.json file in this folder: <project-path>/tests/e2e
> ```
> 
> Have you seen this problem?

Did you follow the steps in the README.md ? it specifies to create a tsconfig file :)

**Comment by maximgeerinck** [comment]
Strange, cypress was upgraded in `dev`, but no changes were made to actually make it compatible

**Comment by svitekpavel** [comment]
> > @maximgeerinck I'm getting the following problem when I checked out this commit:
> > ```
> > Could not find a Cypress configuration file.
> > 
> > We looked but did not find a tsconfig.json file in this folder: <project-path>/tests/e2e
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Have you seen this problem?
> 
> Did you follow the steps in the README.md ? it specifies to create a tsconfig file :)

I have `tsconfig` file. This happens as soon as I change the Synpress version from latest published version on NPM to commit hash of this PR. I see you pushed some code overnight.

**Review by drptbl — CHANGES_REQUESTED** [review]
First of all, sorry for taking so long to take a look at this PR.

Is it complete and working?

I think that this PR has completely omitted loading `support` files which are necessary for synpress to work properly (in remote repos), so I assume it's probably not (fully) working?

I have started updating synpress to Cypress@10 on my own (`dev` branch) and it's mostly complete. Just need Cypress team to address one issue which is a blocker:
https://github.com/cypress-io/cypress/issues/23616

I could do a workaround without waiting for a fix, however it would require everyone using synpress in their repo to add custom synpress config to the repository and this is a situation which I want to avoid.

**Comment by maximgeerinck** [comment]
> remote

happy to change it but do you have an example on how to test for **remote repos** ?
At Refinable we're running this setup within a CI successfully for over a month now (as well as locally)

**Comment by drptbl** [comment]
@maximgeerinck @rohaanmalik @GustavoRSSilva @ezpuzz @Afitzy98 @hardingjam @svitekpavel

Hey,
just wanted to let you know that this is now released as [`@synthetixio/synpress@2.0.0`](https://github.com/Synthetixio/synpress/releases/tag/2.0.0).

Please keep in mind that `support.js` file is now required, take a look at updated [readme](https://github.com/Synthetixio/synpress#-example-setup-for-eslint-and-tsconfig).

**Comment by drptbl** [comment]
Hey, I'm closing this PR for now as we have playwright instead of puppeteer and basically most of the code has been done.

Please reopen if no, thank you!

**Pull request closed without merging**
