### PR TITLE
fix: fixed metamask commands to support v11.15.5

### PR DESCRIPTION
**Pull request by fullstackninja864**
## Motivation and context

Current version of synpress was missing some commands to setup latest metamask v11.15.5.
In this PR we have fixed First time flow, Main page, Notification and setting page selectors.

## Does it fix any issue?

#(issue)

## Other useful info

N/A

## Quality checklist

- [x] I have performed a self-review of my code.

**⚠️👆 Delete any section you see irrelevant before submitting the pull request 👆⚠️**

### CODE REVIEW

**Comment by fullstackninja864** [comment]
@drptbl In my latest [commit](https://github.com/Synthetixio/synpress/pull/1132/commits/fe5a9be332c98298f3c21e7afc75ff43d42b7203) i have added `packageManager` (as testcase were failing because of it). let me know if there is any change required to get this issue fixed .
Thanks

**Comment by abdullah-almesbahi** [comment]
@drptbl we need this PR to be merged ASAP, e2e stopped working because the new version of google chrome 125 is not compatible with metamask 10.25.0

**Comment by drptbl** [comment]
> @drptbl we need this PR to be merged ASAP, e2e stopped working because the new version of google chrome 125 is not compatible with metamask 10.25.0

This pull request is not working. Tests are failing.

**Comment by fullstackninja864** [comment]
Fixing it, Thankyou for pointing out

**Comment by fullstackninja864** [comment]
@drptbl Can you review the changes

**Pull request merged**
