### PR TITLE
fix: fails to confirm signature with Metamask 10.25.0

### PR DESCRIPTION
**Pull request by YakovL**
## Motivation and context

For now, Synpress fails when trying to use `confirmMetamaskSignatureRequest` command with Metamask 10.25.0:

> cy.task('confirmMetamaskSignatureRequest') failed with the following error:
> 
> > page.waitForSelector: Timeout 30000ms exceeded.
> 
> waiting for locator('.notification .request-signature__footer__sign-button') to be visible

The reason is, it tries to use outdated (BEM) selectors while Metamask has removed those classes. For instance, the confirm button is now `<button class="button btn--rounded btn-primary" data-testid="signature-sign-button" role="button" tabindex="0">Подписать</button>` (ru text here).

The proposed fix is to update them using the `data-testid` attribute: `.request-signature__footer__sign-button` → `[data-testid="signature-sign-button"]`

## Does it fix any issue?

I haven't created an issue, I've decided that it will be better to start a PR.

## Other useful info

This is a spot-fix meaning I've only fixed the issue at hand. You may see in `pages/metamask/notification-page.js` that it already contains some selectors like this. However, you can also see that there are a number of other selectors that are BEM-based and are likely to be outdated (for instance, `.nickname-popover__public-address button`). This means that it's better to review all other selectors and other similar issues (which are likely present).

## Quality checklist

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough e2e tests. – no idea what is called "core" here, but if there were some tests for this, they should be broken now.

**PS** Yeah, it's annoying that Metamask keeps changing things: see [this comment](https://github.com/Synthetixio/synpress/issues/325) – looks like several months earlier the `data-testid` attributes of the buttons were `page-container-footer-next` and `page-container-footer-cancel` 🤦‍♂️. This does need e2e tests that will indicate such regressions.

### CODE REVIEW

**Comment by YakovL** [comment]
Alright, I've found a similar issue with token approval and fixed another pair of selectors

**Comment by YakovL** [comment]
@r3kt-eth well, that's what Metamask within the Synpress run on Chrome shows:

image

As far as I understand, Chrome installs the extension on Cypress run, so it's always of the latest version.

**Comment by YakovL** [comment]
@r3kt-eth unexpectedly, not all signing fails. I've checked the [metamask test dapp](https://metamask.github.io/test-dapp/) and found that
* "Personal Sign" and "Sign Typed Data" work fine without the patch from the first commit and are broken by it;
* while "Sign Typed Data V3" and "Sign Typed Data V4" fail without the patch and work are fixed by it.

I've checked the DOM of the confirmation window, and found that Metamask did a good job of messing things up. Below are the outerHTML bits of the 4 confirm buttons for the above cases ("Personal Sign", "Sign Typed Data", "Sign Typed Data V3", and "Sign Typed Data V4") for Metamask 10.25.0 (for some reason, this is not the latest one, which is used in Synpress) and for Metamask 10.34.3 (that's what I currently have in my main browser; don't mind the locale):
```
10.25.0
<button class="button btn--rounded btn-primary btn--large request-signature__footer__sign-button" data-testid="request-signature__sign" role="button" tabindex="0">Подписать</button>
<button class="button btn--rounded btn-primary btn--large request-signature__footer__sign-button" data-testid="request-signature__sign" role="button" tabindex="0">Подписать</button>
<button class="button btn--rounded btn-primary" data-testid="signature-sign-button" role="button" tabindex="0">Подписать</button>
<button class="button btn--rounded btn-primary" data-testid="signature-sign-button" role="button" tabindex="0">Подписать</button>

10.34.3
<button class="button btn--rounded btn-primary page-container__footer-button" data-testid="page-container-footer-next" role="button" tabindex="0">Подписать</button>
<button class="button btn--rounded btn-primary page-container__footer-button" data-testid="page-container-footer-next" role="button" tabindex="0">Подписать</button>
<button class="button btn--rounded btn-primary page-container__footer-button" data-testid="page-container-footer-next" role="button" tabindex="0">Подписать</button>
<button class="button btn--rounded btn-primary page-container__footer-button" data-testid="page-container-footer-next" role="button" tabindex="0">Подписать</button>
```
Which can be selected, in summary, with:
* `.request-signature__footer__sign-button` or `[data-testid="request-signature__sign"]` for the first 2 cases in 10.25.0;
* `[data-testid="signature-sign-button"]` for the second 2 cases in 10.25.0;
* `[data-testid="page-container-footer-next"]` for all the cases in 10.34.3.

Likewise, for Cancel button:
```
10.25.0
<button class="button btn--rounded btn-secondary btn--large request-signature__footer__cancel-button" role="button" tabindex="0">Отклонить</button>
<button class="button btn--rounded btn-secondary btn--large request-signature__footer__cancel-button" role="button" tabindex="0">Отклонить</button>
<button class="button btn--rounded btn-secondary" data-testid="signature-cancel-button" role="button" tabindex="0">Отклонить</button>
<button class="button btn--rounded btn-secondary" data-testid="signature-cancel-button" role="button" tabindex="0">Отклонить</button>
10.34.3
<button class="button btn--rounded btn-secondary page-container__footer-button page-container__footer-button__cancel" data-testid="page-container-footer-cancel" role="button" tabindex="0">Отклонить</button>
<button class="button btn--rounded btn-secondary page-container__footer-button page-container__footer-button__cancel" data-testid="page-container-footer-cancel" role="button" tabindex="0">Отклонить</button>
<button class="button btn--rounded btn-secondary page-container__footer-button page-container__footer-button__cancel" data-testid="page-container-footer-cancel" role="button" tabindex="0">Отклонить</button>
<button class="button btn--rounded btn-secondary page-container__footer-button page-container__footer-button__cancel" data-testid="page-container-footer-cancel" role="button" tabindex="0">Отклонить</button>
```
Note: Cancel button doesn't "always" have `data-testid`, it's `.request-signature__footer__cancel-button`, `[data-testid="signature-cancel-button"]`, or `[data-testid="page-container-footer-cancel"]`.

Thus, instead of switching `confirmSignatureRequestButton` and `rejectSignatureRequestButton` to the new selectors, it's more robust to switch them to the "or" selectors:
```
const confirmSignatureRequestButton =
  `${notificationPage} [data-testid="signature-sign-button"], ` +
  `${notificationPage} [data-testid="page-container-footer-next"], ` +
  `${notificationPage} [data-testid="request-signature__sign"]`;
const rejectSignatureRequestButton =
  `${notificationPage} [data-testid="signature-cancel-button"], ` +
  `${notificationPage} .request-signature__footer__cancel-button, ` +
  `${notificationPage} [data-testid="page-container-footer-cancel"]`;
```
I've added a commit that implements this instead of the previous ones.

**Comment by YakovL** [comment]
@r3kt-eth as for a minimal reproducible example, try this branch: https://github.com/YakovL/synpress-cucumber/tree/confirm-mcve. In syn+dapp_test.cy.ts, you can switch the case ("Personal Sign"/"Sign Typed Data"/"Sign Typed Data V3"/"Sign Typed Data V4") in the "When we press Sign on the Personal Sign card" step by switching the id `signTypedDataV3` to the others from comments. For me, running with `personalSign` and `signTypedData` works and running with `signTypedDataV3` and `signTypedDataV4` fails.

**Comment by YakovL** [comment]
Looks related:
#760 (should be covered by the fix suggested above)
#827 (self-closed, but suggested a similar fix; should be covered by the fix suggested above)
#736 (a similar issue, resolved)

**Comment by YakovL** [comment]
Hi @r3kt-eth were you able to reproduce the issue using the repo I've linked [above](https://github.com/Synthetixio/synpress/pull/828#issuecomment-1685298238)?

**Comment by duckception** [comment]
Hey @YakovL!

Due to legacy reasons, we currently support only MetaMask version `10.25.0`. We're currently working on some major changes to Synpress, and hopefully, we will soon support the latest MetaMask version. Based on this assumption, there's no point in changing the selectors that are working.

Regarding your problem, I've played a bit with your repo and everything seems to work just fine after a few changes. There's one notable thing that you have to keep in mind, which in my opinion, is quite annoying when it comes to using Synpress. For `personal_sign` and `eth_signTypedData` requests you should be using the `cy.confirmMetamaskSignatureRequest()` function, while for `eth_signTypedData_v3` and `eth_signTypedData_v4` requests you should be using the `cy.confirmMetamaskDataSignatureRequest()` function. I'll push for unification of these functions in the future 🫡

Here's a modified test file from your repository that works:
```typescript
When('we press Sign on the Personal Sign card', () => {
  cy.get('#personalSign').click();
});

When('we confirm signing for Personal Sign', () => {
  cy.confirmMetamaskSignatureRequest();
});

Then('result should appear for Personal Sign', () => {
  cy.get('#personalSignResult').should('not.have.text', '');
});

When('we press Sign on the Sign Typed Data card', () => {
  cy.get('#signTypedData').click();
});

When('we confirm signing for Sign Typed Data', () => {
  cy.confirmMetamaskSignatureRequest();
});

Then('result should appear for Sign Typed Data', () => {
  cy.get('#signTypedDataResult').should('not.have.text', '');
});

When('we press Sign on the Sign Typed Data V3 card', () => {
  cy.get('#signTypedDataV3').click();
});

When('we confirm signing for Sign Typed Data V3', () => {
  cy.confirmMetamaskDataSignatureRequest();
});

Then('result should appear for Sign Typed Data V3', () => {
  cy.get('#signTypedDataV3Result').should('not.have.text', '');
});

When('we press Sign on the Sign Typed Data V4 card', () => {
  cy.get('#signTypedDataV4').click();
});

When('we confirm signing for Sign Typed Data V4', () => {
  cy.confirmMetamaskDataSignatureRequest();
});

Then('result should appear for Sign Typed Data V4', () => {
  cy.get('#signTypedDataV4Result').should('not.have.text', '');
});
```

Let me know if you have any more questions and I'll be sure to help out 🫡

PS. Join our [Discord](https://discord.gg/XhZKSRGtWc), where you'll get faster responses to your problems 👀

**Comment by duckception** [comment]
Closing as per my last comment

**Pull request closed without merging**
