### PR TITLE
Add Yarn PnP support

### PR DESCRIPTION
**Pull request by einaralex**
This will resolve both `node_modules/@synthetixio/synpress` and the [Yarn PnP](https://yarnpkg.com/features/pnp) equivalent, which is something like `.yarn/cache/@synthetixio-synpress-npm-{version&hash}.zip/node_modules/@synthetixio/synpress `.

### CODE REVIEW

**Comment by drptbl** [comment]
Hey @einaralex. Thanks for pull request. I'm going to take a look at it until end of the week, test it out and merge.

Cheers,
Jakub.

**Comment by einaralex** [comment]
Hey @drptbl , any updates ?

**Comment by drptbl** [comment]
Hey @einaralex, sorry for delay. I have been affected by the war on Ukraine, but I'm back now. Thanks for contribution.

**Comment by einaralex** [comment]
@drptbl I am so sorry to hear, first and foremost take care of you and your family 🙏
Thank you so much!

**Comment by drptbl** [comment]
@einaralex Thanks for kind words ❤️. That's exactly what I have done past 2 weeks 👍.

Yarn support has been released on `@synthetixio/synpress@1.1.2-beta.3`.

All best,
Jakub.

**Pull request merged**
